# Generated by Django 4.2.11 on 2025-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speed', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('PPPoE', 'PPPoE'), ('Hotspot', 'Hotspot')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
