# Generated by Django 4.2.11 on 2025-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_start', models.DateTimeField(blank=True, null=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
    ]
